spring:
  boot:
      admin:
        client:
          url: http://localhost:9294
          username: admin
          password: admin
  management:
    security:
        enabled: false
    endpoints:
      web:      
        exposure:
          include: "*"
    endpoint:
      web:      
        health:
          show-details: always

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8167/eureka/
  instance:
    hostname:localhost
