eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: DESKTOP-27A0F63
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8167/eureka/

security:
  oauth2:
    client:
      clientId: test
      clientSecret: temp
    resource:
      tokenInfoUri: http://DESKTOP-27A0F63:7777/oauth/check_token
